//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanApplicationWCFService.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankDetailsModel", Namespace="http://schemas.datacontract.org/2004/07/LoanApplicationWCFService.Models")]
    public partial class BankDetailsModel : object
    {
        private string BankAccountNumberField;
        
        private System.Guid BankIdField;
        
        private string BankNameField;
        
        private System.Guid CustomerIdField;
        
        private string IFSCCodeField;
        
       
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccountNumber
        {
            get
            {
                return this.BankAccountNumberField;
            }
            set
            {
                this.BankAccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BankId
        {
            get
            {
                return this.BankIdField;
            }
            set
            {
                this.BankIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName
        {
            get
            {
                return this.BankNameField;
            }
            set
            {
                this.BankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IFSCCode
        {
            get
            {
                return this.IFSCCodeField;
            }
            set
            {
                this.IFSCCodeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBankDetailsService")]
public interface IBankDetailsService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankDetailsService/AddBankDetails", ReplyAction="http://tempuri.org/IBankDetailsService/AddBankDetailsResponse")]
    void AddBankDetails(LoanApplicationWCFService.Models.BankDetailsModel BankDetails);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankDetailsService/AddBankDetails", ReplyAction="http://tempuri.org/IBankDetailsService/AddBankDetailsResponse")]
    System.Threading.Tasks.Task AddBankDetailsAsync(LoanApplicationWCFService.Models.BankDetailsModel BankDetails);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankDetailsService/UpdateBankDetails", ReplyAction="http://tempuri.org/IBankDetailsService/UpdateBankDetailsResponse")]
    void UpdateBankDetails(LoanApplicationWCFService.Models.BankDetailsModel BankDetails, System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankDetailsService/UpdateBankDetails", ReplyAction="http://tempuri.org/IBankDetailsService/UpdateBankDetailsResponse")]
    System.Threading.Tasks.Task UpdateBankDetailsAsync(LoanApplicationWCFService.Models.BankDetailsModel BankDetails, System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankDetailsService/DeleteBankDetails", ReplyAction="http://tempuri.org/IBankDetailsService/DeleteBankDetailsResponse")]
    void DeleteBankDetails(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankDetailsService/DeleteBankDetails", ReplyAction="http://tempuri.org/IBankDetailsService/DeleteBankDetailsResponse")]
    System.Threading.Tasks.Task DeleteBankDetailsAsync(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankDetailsService/GetAllBankDetails", ReplyAction="http://tempuri.org/IBankDetailsService/GetAllBankDetailsResponse")]
    LoanApplicationWCFService.Models.BankDetailsModel[] GetAllBankDetails();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankDetailsService/GetAllBankDetails", ReplyAction="http://tempuri.org/IBankDetailsService/GetAllBankDetailsResponse")]
    System.Threading.Tasks.Task<LoanApplicationWCFService.Models.BankDetailsModel[]> GetAllBankDetailsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankDetailsService/GetBankDetailsById", ReplyAction="http://tempuri.org/IBankDetailsService/GetBankDetailsByIdResponse")]
    LoanApplicationWCFService.Models.BankDetailsModel GetBankDetailsById(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankDetailsService/GetBankDetailsById", ReplyAction="http://tempuri.org/IBankDetailsService/GetBankDetailsByIdResponse")]
    System.Threading.Tasks.Task<LoanApplicationWCFService.Models.BankDetailsModel> GetBankDetailsByIdAsync(System.Guid Id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBankDetailsServiceChannel : IBankDetailsService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BankDetailsServiceClient : System.ServiceModel.ClientBase<IBankDetailsService>, IBankDetailsService
{

    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    public BankDetailsServiceClient(string endPointAddress) :
                base(BankDetailsServiceClient.GetDefaultBinding(), BankDetailsServiceClient.GetDefaultEndpointAddress(endPointAddress))
    {
        this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IBankDetailsService.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public BankDetailsServiceClient(EndpointConfiguration endpointConfiguration, string endPointAddress) :
            base(BankDetailsServiceClient.GetBindingForEndpoint(endpointConfiguration), BankDetailsServiceClient.GetEndpointAddress(endpointConfiguration, endPointAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public BankDetailsServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress, string endPointAddress) :
            base(BankDetailsServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public BankDetailsServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
            base(BankDetailsServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public BankDetailsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }
    public void AddBankDetails(LoanApplicationWCFService.Models.BankDetailsModel BankDetails)
    {
        base.Channel.AddBankDetails(BankDetails);
    }
    
    public System.Threading.Tasks.Task AddBankDetailsAsync(LoanApplicationWCFService.Models.BankDetailsModel BankDetails)
    {
        return base.Channel.AddBankDetailsAsync(BankDetails);
    }
    
    public void UpdateBankDetails(LoanApplicationWCFService.Models.BankDetailsModel BankDetails, System.Guid id)
    {
        base.Channel.UpdateBankDetails(BankDetails, id);
    }
    
    public System.Threading.Tasks.Task UpdateBankDetailsAsync(LoanApplicationWCFService.Models.BankDetailsModel BankDetails, System.Guid id)
    {
        return base.Channel.UpdateBankDetailsAsync(BankDetails, id);
    }
    
    public void DeleteBankDetails(System.Guid id)
    {
        base.Channel.DeleteBankDetails(id);
    }
    
    public System.Threading.Tasks.Task DeleteBankDetailsAsync(System.Guid id)
    {
        return base.Channel.DeleteBankDetailsAsync(id);
    }
    
    public LoanApplicationWCFService.Models.BankDetailsModel[] GetAllBankDetails()
    {
        return base.Channel.GetAllBankDetails();
    }
    
    public System.Threading.Tasks.Task<LoanApplicationWCFService.Models.BankDetailsModel[]> GetAllBankDetailsAsync()
    {
        return base.Channel.GetAllBankDetailsAsync();
    }
    
    public LoanApplicationWCFService.Models.BankDetailsModel GetBankDetailsById(System.Guid Id)
    {
        return base.Channel.GetBankDetailsById(Id);
    }
    
    public System.Threading.Tasks.Task<LoanApplicationWCFService.Models.BankDetailsModel> GetBankDetailsByIdAsync(System.Guid Id)
    {
        return base.Channel.GetBankDetailsByIdAsync(Id);
    }

    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }

    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }

    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBankDetailsService))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration, string endPointAddress)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBankDetailsService))
        {
            return new System.ServiceModel.EndpointAddress(endPointAddress);
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return BankDetailsServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IBankDetailsService);
    }

    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress(string endPointAddress)
    {
        return BankDetailsServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IBankDetailsService, endPointAddress);
    }

    public enum EndpointConfiguration
    {

        BasicHttpBinding_IBankDetailsService,
    }
}
