//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanApplicationWCFService.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanEMIModel", Namespace="http://schemas.datacontract.org/2004/07/LoanApplicationWCFService.Models")]
    public partial class LoanEMIModel : object
    {
        private decimal EMIAmoutField;
        
        private System.Guid EMIIdField;
        
        private int EMINoField;
        
        private string EMIPaymentDateField;
        
        private System.Guid LoanIdField;
        
       
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EMIAmout
        {
            get
            {
                return this.EMIAmoutField;
            }
            set
            {
                this.EMIAmoutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EMIId
        {
            get
            {
                return this.EMIIdField;
            }
            set
            {
                this.EMIIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EMINo
        {
            get
            {
                return this.EMINoField;
            }
            set
            {
                this.EMINoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMIPaymentDate
        {
            get
            {
                return this.EMIPaymentDateField;
            }
            set
            {
                this.EMIPaymentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LoanId
        {
            get
            {
                return this.LoanIdField;
            }
            set
            {
                this.LoanIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ILoanEMIService")]
public interface ILoanEMIService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/AddLoanEMI", ReplyAction="http://tempuri.org/ILoanEMIService/AddLoanEMIResponse")]
    void AddLoanEMI(LoanApplicationWCFService.Models.LoanEMIModel LoanEMI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/AddLoanEMI", ReplyAction="http://tempuri.org/ILoanEMIService/AddLoanEMIResponse")]
    System.Threading.Tasks.Task AddLoanEMIAsync(LoanApplicationWCFService.Models.LoanEMIModel LoanEMI);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/UpdateLoanEMI", ReplyAction="http://tempuri.org/ILoanEMIService/UpdateLoanEMIResponse")]
    void UpdateLoanEMI(LoanApplicationWCFService.Models.LoanEMIModel LoanEMI, System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/UpdateLoanEMI", ReplyAction="http://tempuri.org/ILoanEMIService/UpdateLoanEMIResponse")]
    System.Threading.Tasks.Task UpdateLoanEMIAsync(LoanApplicationWCFService.Models.LoanEMIModel LoanEMI, System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/DeleteLoanEMI", ReplyAction="http://tempuri.org/ILoanEMIService/DeleteLoanEMIResponse")]
    void DeleteLoanEMI(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/DeleteLoanEMI", ReplyAction="http://tempuri.org/ILoanEMIService/DeleteLoanEMIResponse")]
    System.Threading.Tasks.Task DeleteLoanEMIAsync(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/GetAllLoanEMIs", ReplyAction="http://tempuri.org/ILoanEMIService/GetAllLoanEMIsResponse")]
    LoanApplicationWCFService.Models.LoanEMIModel[] GetAllLoanEMIs();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/GetAllLoanEMIs", ReplyAction="http://tempuri.org/ILoanEMIService/GetAllLoanEMIsResponse")]
    System.Threading.Tasks.Task<LoanApplicationWCFService.Models.LoanEMIModel[]> GetAllLoanEMIsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/GetLoanEMIById", ReplyAction="http://tempuri.org/ILoanEMIService/GetLoanEMIByIdResponse")]
    LoanApplicationWCFService.Models.LoanEMIModel GetLoanEMIById(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanEMIService/GetLoanEMIById", ReplyAction="http://tempuri.org/ILoanEMIService/GetLoanEMIByIdResponse")]
    System.Threading.Tasks.Task<LoanApplicationWCFService.Models.LoanEMIModel> GetLoanEMIByIdAsync(System.Guid Id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILoanEMIServiceChannel : ILoanEMIService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LoanEMIServiceClient : System.ServiceModel.ClientBase<ILoanEMIService>, ILoanEMIService
{
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    public LoanEMIServiceClient(string endPointAddress) :
                base(LoanEMIServiceClient.GetDefaultBinding(), LoanEMIServiceClient.GetDefaultEndpointAddress(endPointAddress))
    {
        this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ILoanEMIService.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public LoanEMIServiceClient(EndpointConfiguration endpointConfiguration, string endPointAddress) :
            base(LoanEMIServiceClient.GetBindingForEndpoint(endpointConfiguration), LoanEMIServiceClient.GetEndpointAddress(endpointConfiguration, endPointAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public LoanEMIServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress, string endPointAddress) :
            base(LoanEMIServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public LoanEMIServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
            base(LoanEMIServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public LoanEMIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public void AddLoanEMI(LoanApplicationWCFService.Models.LoanEMIModel LoanEMI)
    {
        base.Channel.AddLoanEMI(LoanEMI);
    }
    
    public System.Threading.Tasks.Task AddLoanEMIAsync(LoanApplicationWCFService.Models.LoanEMIModel LoanEMI)
    {
        return base.Channel.AddLoanEMIAsync(LoanEMI);
    }
    
    public void UpdateLoanEMI(LoanApplicationWCFService.Models.LoanEMIModel LoanEMI, System.Guid id)
    {
        base.Channel.UpdateLoanEMI(LoanEMI, id);
    }
    
    public System.Threading.Tasks.Task UpdateLoanEMIAsync(LoanApplicationWCFService.Models.LoanEMIModel LoanEMI, System.Guid id)
    {
        return base.Channel.UpdateLoanEMIAsync(LoanEMI, id);
    }
    
    public void DeleteLoanEMI(System.Guid id)
    {
        base.Channel.DeleteLoanEMI(id);
    }
    
    public System.Threading.Tasks.Task DeleteLoanEMIAsync(System.Guid id)
    {
        return base.Channel.DeleteLoanEMIAsync(id);
    }
    
    public LoanApplicationWCFService.Models.LoanEMIModel[] GetAllLoanEMIs()
    {
        return base.Channel.GetAllLoanEMIs();
    }
    
    public System.Threading.Tasks.Task<LoanApplicationWCFService.Models.LoanEMIModel[]> GetAllLoanEMIsAsync()
    {
        return base.Channel.GetAllLoanEMIsAsync();
    }
    
    public LoanApplicationWCFService.Models.LoanEMIModel GetLoanEMIById(System.Guid Id)
    {
        return base.Channel.GetLoanEMIById(Id);
    }
    
    public System.Threading.Tasks.Task<LoanApplicationWCFService.Models.LoanEMIModel> GetLoanEMIByIdAsync(System.Guid Id)
    {
        return base.Channel.GetLoanEMIByIdAsync(Id);
    }
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }

    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }

    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILoanEMIService))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration, string endPointAddress)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILoanEMIService))
        {
            return new System.ServiceModel.EndpointAddress(endPointAddress);
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return LoanEMIServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ILoanEMIService);
    }

    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress(string endPointAddress)
    {
        return LoanEMIServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ILoanEMIService, endPointAddress);
    }

    public enum EndpointConfiguration
    {

        BasicHttpBinding_ILoanEMIService,
    }
}
