//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNetCore.Server.Kestrel;

namespace LoanApplicationWCFService.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerModel", Namespace="http://schemas.datacontract.org/2004/07/LoanApplicationWCFService.Models")]
    public partial class CustomerModel : object
    {
        
        
        
        private string AddressProofField;
        
        private string AddressProofNumberField;
        
        private string DateOfBirthField;
        
        private string EmailAddressField;
        
        private string EmploymentTypeField;
        
        private string FirstNameField;
        
        private System.Guid IdField;
        
        private decimal IncomeField;
        
        private string LastNameField;
        
        private string MaritialStatusField;
        
        private string PanCardNumberField;
        
        private string PasswordField;
        
        private string PhoneNumberField;
        
       
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressProof
        {
            get
            {
                return this.AddressProofField;
            }
            set
            {
                this.AddressProofField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressProofNumber
        {
            get
            {
                return this.AddressProofNumberField;
            }
            set
            {
                this.AddressProofNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmploymentType
        {
            get
            {
                return this.EmploymentTypeField;
            }
            set
            {
                this.EmploymentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Income
        {
            get
            {
                return this.IncomeField;
            }
            set
            {
                this.IncomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritialStatus
        {
            get
            {
                return this.MaritialStatusField;
            }
            set
            {
                this.MaritialStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PanCardNumber
        {
            get
            {
                return this.PanCardNumberField;
            }
            set
            {
                this.PanCardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICustomerService")]
public interface ICustomerService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerResponse")]
    void AddCustomer(LoanApplicationWCFService.Models.CustomerModel customer);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerResponse")]
    System.Threading.Tasks.Task AddCustomerAsync(LoanApplicationWCFService.Models.CustomerModel customer);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/DeleteCustomer", ReplyAction="http://tempuri.org/ICustomerService/DeleteCustomerResponse")]
    void DeleteCustomer(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/DeleteCustomer", ReplyAction="http://tempuri.org/ICustomerService/DeleteCustomerResponse")]
    System.Threading.Tasks.Task DeleteCustomerAsync(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetAllCustomersResponse")]
    LoanApplicationWCFService.Models.CustomerModel[] GetAllCustomers();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetAllCustomersResponse")]
    System.Threading.Tasks.Task<LoanApplicationWCFService.Models.CustomerModel[]> GetAllCustomersAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerById", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerByIdResponse")]
    LoanApplicationWCFService.Models.CustomerModel GetCustomerById(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerById", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerByIdResponse")]
    System.Threading.Tasks.Task<LoanApplicationWCFService.Models.CustomerModel> GetCustomerByIdAsync(System.Guid Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomer", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerResponse")]
    void UpdateCustomer(LoanApplicationWCFService.Models.CustomerModel customer, System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateCustomer", ReplyAction="http://tempuri.org/ICustomerService/UpdateCustomerResponse")]
    System.Threading.Tasks.Task UpdateCustomerAsync(LoanApplicationWCFService.Models.CustomerModel customer, System.Guid id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICustomerServiceChannel : ICustomerService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CustomerServiceClient : System.ServiceModel.ClientBase<ICustomerService>, ICustomerService
{

    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    public CustomerServiceClient(string endPointAddress) :
               base(CustomerServiceClient.GetDefaultBinding(), CustomerServiceClient.GetDefaultEndpointAddress(endPointAddress))
    {

        this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICustomerService.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    public CustomerServiceClient(EndpointConfiguration endpointConfiguration, string endPointAddress) :
                 base(CustomerServiceClient.GetBindingForEndpoint(endpointConfiguration), CustomerServiceClient.GetEndpointAddress(endpointConfiguration, endPointAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public CustomerServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress, string endPointAddress) :
            base(CustomerServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public CustomerServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
            base(CustomerServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }


    public void AddCustomer(LoanApplicationWCFService.Models.CustomerModel customer)
    {
        base.Channel.AddCustomer(customer);
    }
    
    public System.Threading.Tasks.Task AddCustomerAsync(LoanApplicationWCFService.Models.CustomerModel customer)
    {
        return base.Channel.AddCustomerAsync(customer);
    }
    
    public void DeleteCustomer(System.Guid id)
    {
        base.Channel.DeleteCustomer(id);
    }
    
    public System.Threading.Tasks.Task DeleteCustomerAsync(System.Guid id)
    {
        return base.Channel.DeleteCustomerAsync(id);
    }
    
    public LoanApplicationWCFService.Models.CustomerModel[] GetAllCustomers()
    {
        return base.Channel.GetAllCustomers();
    }
    
    public System.Threading.Tasks.Task<LoanApplicationWCFService.Models.CustomerModel[]> GetAllCustomersAsync()
    {
        return base.Channel.GetAllCustomersAsync();
    }
    
    public LoanApplicationWCFService.Models.CustomerModel GetCustomerById(System.Guid Id)
    {
        return base.Channel.GetCustomerById(Id);
    }
    
    public System.Threading.Tasks.Task<LoanApplicationWCFService.Models.CustomerModel> GetCustomerByIdAsync(System.Guid Id)
    {
        return base.Channel.GetCustomerByIdAsync(Id);
    }
    
    public void UpdateCustomer(LoanApplicationWCFService.Models.CustomerModel customer, System.Guid id)
    {
        base.Channel.UpdateCustomer(customer, id);
    }
    
    public System.Threading.Tasks.Task UpdateCustomerAsync(LoanApplicationWCFService.Models.CustomerModel customer, System.Guid id)
    {
        return base.Channel.UpdateCustomerAsync(customer, id);
    }

    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }

    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }

    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerService))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration, string endPointAddress)
    {
        if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerService))
        {

            return new System.ServiceModel.EndpointAddress(endPointAddress);
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return CustomerServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICustomerService);
    }

    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress(string endPointAddress)
    {
        return CustomerServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICustomerService, endPointAddress);
    }

    public enum EndpointConfiguration
    {

        BasicHttpBinding_ICustomerService,
    }
}
